{% set version = '0.3-5' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gsignal
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gsignal_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gsignal/gsignal_{{ version }}.tar.gz
  sha256: 4ebf509626ad7f7ed7e67269958cf135c1de22a703acf8a6e94e9fb7d145cb63

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-pracma
  run:
    - r-base
    - r-rcpp
    - r-pracma

test:
  commands:
    - $R -e "library('gsignal')"           # [not win]
    - "\"%R%\" -e \"library('gsignal')\""  # [win]

about:
  home: https://github.com/gjmvanboxtel/gsignal
  license: GPL-3.0-only
  summary: |
    R implementation of the 'Octave' package 'signal', containing a 
    variety of signal processing tools, such as signal generation and 
    measurement, correlation and convolution, filtering, filter design, 
    filter analysis and conversion, power spectrum analysis, system 
    identification, decimation and sample rate change, and windowing.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - inst/COPYRIGHTS

extra:
  recipe-maintainers:
    - conda-forge/r
    - dipterix
